### ISSUE TITLE
Losing connecting to UniFi Protect causes sensors to stop updating. Needed to restart integration.

### ISSUE THREAD

**Issue by Mulle00** [briis/unifiprotect#441]
### Home Assistant Version?

2021.12.7

### UniFi Protect Version?

1.20.3

### UniFi Protect HA Integration version?

0.12.0-beta5

### What happened?

If the Protect App crashes on the UNVR and restarts itself, then all sensors are no longer updated in HA.

A restart of the integration in HA is required to get it back active.

Simulating by stopping and restarting the Protect App on the UNVR will not cause the same problem. Everything continues to work perfectly.

The crash was around 9:36 and the restart was around 9:41.

Screenshot after the crash:
![after crash](https://user-images.githubusercontent.com/25512372/147914146-74ddb2c7-9d9b-4c25-9dbf-3bbb86d6b9c5.png)

Screenshot after restart:
![after restart](https://user-images.githubusercontent.com/25512372/147914152-b1c405da-4720-43b6-b49f-0b14dede16f5.png)

I had the same problem with the latest stable integration

Logs:
[logs.txt](https://github.com/briis/unifiprotect/files/7801121/logs.txt)

### Relevant log output

```shell
See uploaded file (too big)
```

**Comment by AngellusMortis** [comment]
I am doing more extensive debugging right now, but in your case, I do not think there is much I can do from my end. Your UniFi Protect application is basically just constantly crashing. 

It looks like it reconnects correctly, but once it starts crashing it just crashes, about a minute comes back and then about a minute later crashes again. 

You can try to install the `master` version, that has code with a lot more logging in it that I backported from the WIP core version of the integration. I am running it on my HA version right now to test reconnects. If you post more debug logs, you may want to use https://gist.github.com/ instead and then DM to me on the Home Assistant forums (same username).

**Comment by MartinTerp** [comment]
It also happends if you update protect/nvr/cloudkey

**Comment by AngellusMortis** [comment]
The updates for sure have been fixed if you are on the latest 0.12-beta. I have been running my HA instance with verbose logging on for the past few days and any disconnects I have gotten are recovering as expected. 

I suspect it is only real a big issue for if your UniFi Protect instance is crashes a lot.

**Comment by MartinTerp** [comment]
Well, i just updated my cloudkey (unifi os), and when it was back online, HA coudnt find the entities anymore, after reload of the addon in hacs, it worked again.

HA: Home Assistant 2021.12.7
UniFi OS Version: 2.3.10
Protect: 1.21.0-beta.2
This addon: v0.12.0-beta5

**Comment by AngellusMortis** [comment]
Ah! I finally got something new to happen to me. It looks like it might be a thundering herd problem. 

HA is prioritizing async tasks for updating devices over the WS reconnect task. So, every time a device update is triggered, it reset the WS reconnect task and never actually schedules and executes the reconnect task. Going to do some more debugging and see if my fix improves it.

**Comment by AngellusMortis** [comment]
Okay. 0.12.0-beta8 is out. Should greatly improve the Websocket reconnects after Protect goes offline. Let me know if you guys have any issues with Protect reconnecting. Make sure you check the logs on the current state of the Websocket! You get a WARNING log message on disconnect and an INFO log message on reconnect. 

Let me know if you see entities no recoveries still after a UniFi Protect reboot/disconect.

**Comment by MarvinSchenkel** [comment]
I still have issues with the latest beta. It sees to reconnect fine as all my entities come back as 'available' after the Protect app crashes. However, whenever someone rings my doorbell, the `binary_sensor` does not change status, which means my automations do not fire. A restart of the integration fixes this problem temporarily.

**Comment by AngellusMortis** [comment]
It falls back to polling if the Websocket connection cannot be made. So, your entities being online does not mean your Websocket is connected. The doorbell is not work unless the Websocket is running since it is such a short period. 

You have to look at your logs and see if you have a "Websocket connected" message. If you do not, HA is not able to reconnect to UniFi Protect for some reason. You can [enable debug logging](https://github.com/briis/unifiprotect#enable-debug-logging) for pyunifiprotect and post them. My guess is that HA is just not letting the reconnect task go through.

**Comment by MarvinSchenkel** [comment]
> It falls back to polling if the Websocket connection cannot be made. So, your entities being online does not mean your Websocket is connected. The doorbell is not work unless the Websocket is running since it is such a short period.
> 
> You have to look at your logs and see if you have a "Websocket connected" message. If you do not, HA is not able to reconnect to UniFi Protect for some reason. You can [enable debug logging](https://github.com/briis/unifiprotect#enable-debug-logging) for pyunifiprotect and post them. My guess is that HA is just not letting the reconnect task go through.

I pulled some logs, the crash of Protect happened at 15:42:04. The attached file includes the log lines I thought were relevant, if you need more, please let me know.

[unifi_protect_log.txt](https://github.com/briis/unifiprotect/files/7841179/unifi_protect_log.txt)

**Comment by AngellusMortis** [comment]
v0.12.0-beta9 has some more improvements. Please let me know if that helps you guys some more. Please try it out and get me some fresh logs if you are still having a lot of issues. I will keep track of my instance as well.

**Comment by Mulle00** [comment]
Thanks for the many and quick improvements. Unfortunately I can't test it anymore, because since the new HDD everything works perfectly.

Only I had a strange occurrence in HA when replacing the HDD. After replacing the HDD I put the backups back. In HA, the current entities of protect are no longer used, but new ones were created. So I had to delete my old ones and rename the new ones again.

**Comment by AngellusMortis** [comment]
> In HA, the current entities of protect are no longer used, but new ones were created.

Yeah, I think I noticed that when I replaced my HDDs in my UNVR as well. The device IDs seem to change when you swap the harddrives. I would have to do another entity ID migration to fix that, which is quite a bit of a pain. 

A tip for general HA guidance: I have really gotten into the habit of _not_ renaming my entities if I can avoid it. Instead rename wherever they come from (so with this Integration, rename in UniFi Protect, for ZWaveJS2Mqtt, rename in ZWaveJS2Mqtt, etc.). That makes it so I can just nuke the integration whenever I want and re-add it and all of the entities will just get fixed.

**Comment by MarvinSchenkel** [comment]
Unfortunately no dice with beta-9.
[unifi_protect_log.txt](https://github.com/briis/unifiprotect/files/7864630/unifi_protect_log.txt)

The Protect crash happened at 11:37:45. It does mention it reconnected successfully but then switches back to polling. Ringing the doorbell does not change the state of the associated binary sensor.

**Comment by AngellusMortis** [comment]
Okay, we re-wrote the Websocket code for 0.12.0-beta10. I am pretty sure I found exactly what the issue was that was causing reconnect issues and fixed it (as well more general code improvements).

**Comment by MarvinSchenkel** [comment]
Updated to beta10 and unfortunately, I still do not receive any state changes to the binary_sensor when my doorbell is rung. Looking at the log, it is now constantly looping the following messages every 5 sec:
``` 
2022-01-17 13:23:09 DEBUG (MainThread) [pyunifiprotect.websocket] Scheduling WS connect...
2022-01-17 13:23:09 DEBUG (MainThread) [pyunifiprotect.websocket] Connecting WS to wss://192.168.1.96/proxy/protect/ws/updates?lastUpdateId=cdb44d57-839f-481e-8408-8f4bc5049737
2022-01-17 13:23:09 DEBUG (MainThread) [pyunifiprotect.websocket] WS timeout reset
2022-01-17 13:23:09 INFO (MainThread) [pyunifiprotect.websocket] Connected to Websocket successfully
2022-01-17 13:23:09 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2022-01-17 13:23:09 DEBUG (MainThread) [pyunifiprotect.websocket] Websocket disconnected
2022-01-17 13:23:14 DEBUG (MainThread) [pyunifiprotect.websocket] Scheduling WS connect...
2022-01-17 13:23:14 DEBUG (MainThread) [pyunifiprotect.websocket] Connecting WS to wss://192.168.1.96/proxy/protect/ws/updates?lastUpdateId=cdb44d57-839f-481e-8408-8f4bc5049737
2022-01-17 13:23:14 DEBUG (MainThread) [pyunifiprotect.websocket] WS timeout reset
2022-01-17 13:23:14 INFO (MainThread) [pyunifiprotect.websocket] Connected to Websocket successfully
2022-01-17 13:23:14 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2022-01-17 13:23:14 DEBUG (MainThread) [pyunifiprotect.websocket] Websocket disconnected
2022-01-17 13:23:19 DEBUG (MainThread) [pyunifiprotect.websocket] Scheduling WS connect...
2022-01-17 13:23:19 DEBUG (MainThread) [pyunifiprotect.websocket] Connecting WS to wss://192.168.1.96/proxy/protect/ws/updates?lastUpdateId=cdb44d57-839f-481e-8408-8f4bc5049737
2022-01-17 13:23:19 DEBUG (MainThread) [pyunifiprotect.websocket] WS timeout reset
2022-01-17 13:23:19 INFO (MainThread) [pyunifiprotect.websocket] Connected to Websocket successfully
2022-01-17 13:23:19 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2022-01-17 13:23:19 DEBUG (MainThread) [pyunifiprotect.websocket] Websocket disconnected
2022-01-17 13:23:24 DEBUG (MainThread) [pyunifiprotect.websocket] Scheduling WS connect...
2022-01-17 13:23:24 DEBUG (MainThread) [pyunifiprotect.websocket] Connecting WS to wss://192.168.1.96/proxy/protect/ws/updates?lastUpdateId=cdb44d57-839f-481e-8408-8f4bc5049737
2022-01-17 13:23:24 DEBUG (MainThread) [pyunifiprotect.websocket] WS timeout reset
2022-01-17 13:23:24 INFO (MainThread) [pyunifiprotect.websocket] Connected to Websocket successfully
2022-01-17 13:23:24 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2022-01-17 13:23:24 DEBUG (MainThread) [pyunifiprotect.websocket] Websocket disconnected
2022-01-17 13:23:29 DEBUG (MainThread) [pyunifiprotect.websocket] Scheduling WS connect...
2022-01-17 13:23:29 DEBUG (MainThread) [pyunifiprotect.websocket] Connecting WS to wss://192.168.1.96/proxy/protect/ws/updates?lastUpdateId=cdb44d57-839f-481e-8408-8f4bc5049737
2022-01-17 13:23:29 DEBUG (MainThread) [pyunifiprotect.websocket] WS timeout reset
2022-01-17 13:23:29 INFO (MainThread) [pyunifiprotect.websocket] Connected to Websocket successfully
2022-01-17 13:23:29 DEBUG (MainThread) [pyunifiprotect.api] Skipping update since websocket is active
2022-01-17 13:23:29 DEBUG (MainThread) [pyunifiprotect.websocket] Websocket disconnected
```

**Comment by AngellusMortis** [comment]
You actually beat me to it. I was already working on changes to fix those. The issue is reconnections generally work right after the integration starts, they only seem to stop works after it has been a number of hours. Since beta10 basically had a rewrite of the Websocket code, there was a couple of bugs in the code. It is really hard to test code that interacts with real network resources.

Anyways, beta11 has more improvements. I ran the code for beta11 on my own instance for a day this time around before releasing it. I am not seeing anymore reconnect issues. I also found a couple of places we needed more logging, so if you do have issues, we should get more data now.

**Comment by MarvinSchenkel** [comment]
> You actually beat me to it. I was already working on changes to fix those. The issue is reconnections generally work right after the integration starts, they only seem to stop works after it has been a number of hours. Since beta10 basically had a rewrite of the Websocket code, there was a couple of bugs in the code. It is really hard to test code that interacts with real network resources.
> 
> Anyways, beta11 has more improvements. I ran the code for beta11 on my own instance for a day this time around before releasing it. I am not seeing anymore reconnect issues. I also found a couple of places we needed more logging, so if you do have issues, we should get more data now.

No worries, happy to test and provide logs :-). I'll wait for beta11 and report back 👍

**Comment by MarvinSchenkel** [comment]
4 days and still going strong! Looks like beta11 did the trick

**Comment by AngellusMortis** [comment]
I am going to close this one as hopefully finally fixed.
